# GENERATED BY GEMINI PRO

import json
import os
import re

def extract_first_two_sentences(text):
    """Splits text by sentence-ending punctuation, ignoring periods inside URLs."""
    # Split on period, question mark, or exclamation mark that is followed by a space
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    # Filter out any empty strings
    sentences = [s.strip() for s in sentences if s.strip()]
    return " ".join(sentences[:2]) if len(sentences) > 0 else text

def format_sources(sources, include_type=False):
    """Formats the sources and similarity scores into HTML lists so they fit in markdown tables."""
    source_html = "<ul>"
    scores_html = "<ul>"
    for s in sources:
        # Check if cross-corpus tracking is needed
        type_str = f" <i>({s.get('source_type', '')})</i>" if include_type and 'source_type' in s else ""
        
        source_html += f"<li><b>{s['title']}</b><br><code>{s['url']}</code>{type_str}</li>"
        scores_html += f"<li>{s['distance']}</li>"
    
    source_html += "</ul>"
    scores_html += "</ul>"
    return source_html, scores_html

def generate_markdown_table(data_file, is_part2=False):
    if not os.path.exists(data_file):
        return f"**Error: {data_file} not found. Did you run the pipeline?**\n"

    with open(data_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Markdown Table Header
    md = "| Query ID & Text | Top K Sources | Similarity | Generated Answer (First 2 Sentences) | Grounded Correctly? |\n"
    md += "|---|---|---|---|---|\n"

    for row in data:
        q_info = f"<b>{row['query_id']}</b><br>{row['query_text']}"
        sources, scores = format_sources(row['top_k_sources'], include_type=is_part2)
        ans_preview = extract_first_two_sentences(row['generated_answer'])
        
        # We leave this blank so you can edit the markdown file and type "Yes" or "No" manually
        grounded = row['grounded_correctly'] if row['grounded_correctly'] else " "

        # Clean up linebreaks so it doesn't break the markdown table format
        ans_preview = ans_preview.replace("\n", " ")

        md += f"| {q_info} | {sources} | {scores} | {ans_preview} | {grounded} |\n"

    return md

def main():
    print("Generating REPORT.md from JSON files...")
    
    # Load configs for the summary
    with open("config.json", "r") as f:
        config = json.load(f)

    report_content = f"""# Assignment 4: Retrieval Augmented Generation
**Track Selected:** Track A, Text RAG (Short)

## Pipeline Summary
This project implements a fully local RAG pipeline to avoid API constraints. The vector database used is Chroma, persisting to `{config['vector_db_path']}`. A subset of the Wikipedia Simple English dataset was embedded locally using the `{config['embedding_model_name']}` sentence-transformer model. The generator leverages the `{config['generator_model_name']}` instruction-tuned model, accessed via a local/VPN endpoint, to synthesize grounded answers from the top $k={config['top_k']}$ retrieved contexts. 

## Part 1: Baseline Queries
{generate_markdown_table('part1_results.json', is_part2=False)}

## Part 2: New Item Queries (Targeted & Cross-Corpus)
{generate_markdown_table('part2_results.json', is_part2=True)}

## Reflection
*(Write 2-3 paragraphs here discussing when retrieval succeeded vs failed, what happened with the cross-corpus Everquest queries, and what you would change about the pipeline.)*
"""

    with open("REPORT.md", "w", encoding="utf-8") as f:
        f.write(report_content)

    print("REPORT.md successfully generated! Please open it to fill out your Yes/No column and write your reflection.")

if __name__ == "__main__":
    main()